### ISSUE TITLE
winbox.default is not a constructor

### ISSUE THREAD

**Issue by DoneDeal0** [nextapps-de/winbox#1]
I'm trying to use your lib in a React project. When importing it with: `import WinBox from "winbox"`, I receive an empty object. So trying to instantiate a new winbox triggers the error: `winbox.default is not a constructor`.

Here is the test code I wrote:

```js
import React from "react";
import WinBox from "winbox";

export default function App() {

  const createModal = () => {
   const modal = new WinBox({
      title: "Set innerHTML",
      html: "<h1>hello</h1>"
    });
    return modal
  };

  console.log("WinBox", WinBox) // returns {}

  return (
    <div>
      <button onClick={createModal}>new modal</button>
    </div>
  );
}
```
Here is a codesandbox: https://codesandbox.io/s/pedantic-bush-lplpl?file=/src/App.tsx

**Comment by 0xnoob** [comment]
for anyone else wandering, you need to import the js from deeper down in the module and the css from another path in the module:

```javascript
import WinBox from "winbox/src/js/winbox";
import "winbox/dist/css/winbox.css";
```

**Comment by forze961** [comment]
If you try use with SSR (NextJS etc) and have some troubles:

1. IF You have this error `“Must use import to load ES Module”` - rename winbox.js to winbox.cjs or write `"type": "module"`;
2. If You have this error `Next.js: document is not defined` - import this module dynamicaly on client. [detail](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr).

P.S. When used in conjunction with nextjs, I did not find answers to these questions. I suppose this might help. Many thanks to the author for such a tool!

**Comment by Bader5110** [comment]
G

**Comment by wobsoriano** [comment]
If you use TypeScript I guess you can only do something like

```typescript
import 'winbox';

declare const WinBox: WinBox.WinBoxConstructor;

export default function useWinBox() {
    return {
        create(options: VueWinBoxOptions) {
            return new WinBox({
                ...options
            })
        }
    }
}
```
