### ISSUE TITLE
minimized window titles are not sorted in the correct z-order if minimize() called at creation time and then another window is minimized

### ISSUE THREAD

**Issue by h3rb** [nextapps-de/winbox#106]
If I have two windows that are already minimized and created during the same time, and a third window that is not minimized and I click the minimize button, it appears behind the third window if it was created before another window that was already minimized.

ie:

(during document ready event):
```
var a = new WinBox({ title: "A Longer Name Than a Letter",  top: 40, x:"center", y:"center", width:600, height:600, class: [ "modern", "no-close", "no-resize", "no-max", "no-full" ] }); a.minimize();
var c = new WinBox({  title: "An unminimized win", top: 40, x:"center", y:"center", width:800, height: 600, class: [ "modern", "no-close", "no-full" ]  });
var b = new WinBox({ title: "Before You Have Clicked", top: 40, x:"center", y:"center", width:500, height: 400, class: [ "modern", "no-close", "no-full" ] }); b.minimize();
```

**Comment by h3rb** [comment]
Note that if I move line "C" below line "B", it still is in the wrong z-order.  Yet, if I un-minimize the windows and then minimize them I cannot reproduce this wrong z-order once it is 'manually refreshed by user'

**Comment by h3rb** [comment]
Since the windows appear in the order (when minimized) of ABC where C is behind B, the "fastest" way to fix the problem is to un-minimize B and then minimize C and then B which corrects the z-order.  If I un-minimize B and then minimize it again, and then minimize C, it will not correct the ordering.

**Comment by ts-thomas** [comment]
Hello. Actually the order of minimized windows is related to the order of when the window was getting minimized, not the order when the window was created. Probably this is getting improved in future.
