### ISSUE TITLE
Any way to make the windows white background, black border?

### ISSUE THREAD

**Issue by Betweenwonders** [nextapps-de/winbox#110]
It seems like I can only create black title bar, white window body. I want to make both the .wb-title and the .wb-body WHITE but with BLACK border -- how would I do this? 

I also want to add some decorations on the title bar as well: anyways to achieve this?
![Front-and-Center-for-Mac-image-001](https://user-images.githubusercontent.com/98209547/155457793-dabf818f-6fb6-47cd-a796-16bbdfc602ad.png)

Much appreciated!

**Comment by ts-thomas** [comment]
The easiest way is just use CSS and style the window. You can use the standard themes as well as the standard winbox css file to get some suggestions.
