### ISSUE TITLE
Limit open windows?

### ISSUE THREAD

**Issue by MadTomT** [nextapps-de/winbox#117]
Hi
Is it possible to limit how many winboxes can be open ?
Is there a way to count them so I can only allow X open at a time ?

Thanks

**Comment by MadTomT** [comment]
I've sorted this using jquery when adding a new window.

```
		if ( $('div[id^=winbox]').length  == 3 ) {
			console.log ( 'max open windows reached' )
			return false
		}
```

**Comment by ts-thomas** [comment]
You can use the winbox callback functions for this purpose.
