### ISSUE TITLE
Resizing iframe using jquery causes issue when manually resizing.

### ISSUE THREAD

**Issue by MadTomT** [nextapps-de/winbox#119]
Hi

I'm resizing my iframe from with in.  To do that I'm using the following on the page that is loaded in the iframe.

`$('#' + iframe-id, window.parent.document).height( newheight );`

This works well and the iframe is resized. 
However if I then try to manually resize the iframe by dragging on the corner, the window jumps back to it's original size before allowing me to resize it.

Anyway around that ?
Thanks

**Comment by ts-thomas** [comment]
You'll need also to apply `width` and `height` of new sized window to the Winbox instance. You cannot set size to a Winbox element manually. You have to use the builtin helper function `.resize()` to do that.
