### ISSUE TITLE
is there any way to change the position of a winbox when it's minimized?

### ISSUE THREAD

**Issue by blinkhd** [nextapps-de/winbox#120]
I want to make it so that when I minimize my winbox, it moves into the bottom right of the screen instead of the bottom left.

**Comment by ts-thomas** [comment]
This is actually not supported. Customize the minimized container is already added as suggestion.

**Comment by MistakingManx** [comment]
For me, I have an issue where it goes straight behind the taskbar, making it impossible to click, so I'm trying to limit how far it can go but i find im having difficulty.

**Comment by JereNurminen** [comment]
Hello! Do you have any updates on this @ts-thomas? We're using Winbox in a product we're building, and being able to customize where minimized windows go would be important to us. If you don't have the time or interest to do this, we can also see if we could do a PR on this ourselves
