### ISSUE TITLE
Use window.inner(Height|Width) instead of document.body.client(Height|Width)

### ISSUE THREAD

**Issue by Tey** [nextapps-de/winbox#121]
When the body height/width is smaller than the window size, `root_h`/`root_w` will be smaller than the window size, so the winboxes will not be able to be moved around all the available space. Please use [window.innerHeight](https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth) and [window.innerWidth](https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight) to set the value of `root_h`/`root_w` in [init()](https://github.com/nextapps-de/winbox/blob/d1088d1ec744a448e71f44eb9ec61bad87f936d5/src/js/winbox.js#L620) instead to prevent that.

Here is an example of the issue: https://jsfiddle.net/pahcfy63/1/ (try moving the winbox down or minimize it)

**Comment by ts-thomas** [comment]
I using this now:

```js
    const doc = document.documentElement;
    root_w = doc.clientWidth;
    root_h = doc.clientHeight;
```
