### ISSUE TITLE
'browser' issue in package.json results in an Empty Object

### ISSUE THREAD

**Issue by smalllong** [nextapps-de/winbox#122]
The file specified in 'browser' field of package.json should export a value (using UMD or CJS) but you directly put an IIFE file here. As a result, the winbox can usually be empty when imported using tools like [Parcel](https://parceljs.org/).

Some prior issues look like caused by this but didn't really got solved:
https://github.com/nextapps-de/winbox/issues/112
https://github.com/nextapps-de/winbox/issues/68
https://github.com/nextapps-de/winbox/issues/1

Please fix the 'browser' value

**Comment by ts-thomas** [comment]
Thanks for this hint.
