### ISSUE TITLE
minwidth or minheight doesn't work with "no-move"

### ISSUE THREAD

**Issue by fafato1** [nextapps-de/winbox#125]
I'm trying to make a sidebar that the user can resize and leave it the way they prefer

Default size: 
![image](https://user-images.githubusercontent.com/18727712/181853106-aa4345af-b1a1-415e-a323-5c425b8c8e3e.png)

Resized below minimum (Yes, he cut the right side of winbox!): 
![image](https://user-images.githubusercontent.com/18727712/181853205-af7da87a-f44f-44e7-87c9-2d9bbbb2ba15.png)

my code:
![image](https://user-images.githubusercontent.com/18727712/181852825-d9bbda85-bbda-4d10-946b-30cf36d0c817.png)

**Comment by ts-thomas** [comment]
Please try again with newest version.

**Comment by fafato1** [comment]
Ok, i'll try

**Comment by ryihan** [comment]
I have same issue...

**Comment by fafato1** [comment]
@ts-thomas I tested now, but now it's "no-move" who don't work!

![image](https://user-images.githubusercontent.com/18727712/188350876-5efa14ec-bf0e-42d6-b6d9-6d49d01513ed.png)
