### ISSUE TITLE
Renaming this project? Please give me your vote ...

### ISSUE THREAD

**Issue by ts-thomas** [nextapps-de/winbox#13]
Before I chose the name WinBox I made some search, but probably not good enough. I've never heard about the router manufacture which uses the same name for one of their toolkit. Personally I'm totally fine with it. But there was another naming candidate for this window manager called "Scalebox" which I did not picked.

Which one would you choose:

1. are you fine with the current name?
2. do you prefer the name "Scalebox"?
3. do you have another suggestion? 

Thanks a lot.

**Comment by FishOrBear** [comment]
window.js

**Comment by fzammetti** [comment]
I actively dislike Scalebox.

I'm fine with the current name despite the conflict... though I'd offer a few suggestions: WebWindow, Aperture, Subview.  I see @FishOrBear 's suggestion of window.js, and that's not bad, but I tend to think there's too many *.js projects already, so for me it wouldn't be my first choice.

**Comment by DmitriyWebDev** [comment]
"winbox" it is a nice name!

**Comment by stopmotio** [comment]
searching "winbox.js" immediately brings up the github pages site... maybe we should use that!

**Comment by andisfar** [comment]
how about js-winbox.js or winbox-js.js

**Comment by stopmotio** [comment]
@andisfar why we need two `js`

**Comment by Pustur** [comment]
[window.js on npm is already taken](https://www.npmjs.com/package/window.js)
[So is WindowJS on GitHub](https://github.com/m-thalmann/windowjs)

I wouldn't choose that. I personally like the current name.

**Comment by ts-thomas** [comment]
I contact the npm support and asking for the window.js package name. They had answered me that they actually work on a new policy, so I have to wait. But the chances are low, because another policy did not allow similar names of existing packages and there is also a package name "window" which will be blocking the "window.js" package name by sure.

I will keep that name. I read some negative responses about the naming, and I just wand to check if I can something improve. But it looks that isn't a really big problem with the current name.

Thanks a lot!
