### ISSUE TITLE
Save and restore windows?

### ISSUE THREAD

**Issue by snaildos** [nextapps-de/winbox#14]
saving windows? Then restoring them?
With local-storage? 🤔

**Comment by ts-thomas** [comment]
I'm thinking about a simple plugin system to extend features optionally. The idea with the local storage is nice, all could be restored except the body content when nodes was mounted to the window body. It would just work to restore when adding HTML string or an URL to create the window. HTML string created nodes could also be modified after insertion e.g. by adding event listeners to it, so they are getting lost also when restoring. Seems to be a robust feature just when using iframe contents.

**Comment by snaildos** [comment]
Great. I think this can be closed then.
