### ISSUE TITLE
Windows with `no-max` class can still be maximized by double clicking the header bar

### ISSUE THREAD

**Issue by RickoNoNo3** [nextapps-de/winbox#150]
When I assigned `no-max` to my winbox, the control button for maximizing was removed, but the window could still be maximized by double clicking the header bar. Is this an unexpected behavior?

BTW, as #143 said, `no-move` is mis-worked as well.

**Comment by RobertoMalatesta** [comment]
I killed it entirely:
**WinBox.prototype.maximize=()=>{}**
But only bc when I noticed it I was in a hurry.
R

**Comment by ts-thomas** [comment]
fixed in v0.2.8
