### ISSUE TITLE
winbox keeps "focus" state after mouse click outside

### ISSUE THREAD

**Issue by gleh** [nextapps-de/winbox#152]
Having two or more winboxes open the windows get focus or blur depending on mouse clicks onto the windows but a single winbox will always have the status "focus".
The winbox state "focus" should also be removed if a mouse click is made outside the winboxes. Switching e.g. background colour is not working thus.

**Comment by ts-thomas** [comment]
added in v0.2.8

**Comment by lemurre** [comment]
Is there a way of _disabling_ this so one window is always in the focus even if you click outside?
