### ISSUE TITLE
how to set title in winbox.addControl

### ISSUE THREAD

**Issue by kobe651jp** [nextapps-de/winbox#153]
It's possible to set title over image(icon)?

Or show message when cursor hover on the image.

**Comment by ts-thomas** [comment]
You can achieve this by applying the title in the `oncreate` callback by using standard Javascript.

```js
WinBox({
    oncreate: function(options){
        const nodes = this.window.querySelectorAll(".wb-title, .wb-icon");
        nodes[0].title = nodes[1].title = "Some title";
    }
});
```
