### ISSUE TITLE
index parameter ignored when initial state is hidden

### ISSUE THREAD

**Issue by Couchy** [nextapps-de/winbox#155]
For example, this doesn't set z-index:
`const winbox = new WinBox({title: "Window Title", hidden: true, autosize: true, index: 2022, mount: frame});`

But this does:
```
const winbox = new WinBox({title: "Window Title", autosize: true, index: 2022, mount: frame});
winbox.hide();
```

See: https://github.com/nextapps-de/winbox/blob/master/src/js/winbox.js#L296

**Comment by ts-thomas** [comment]
fixed in v0.2.8
