### ISSUE TITLE
Scaling or moving windows too quickly can cause them to "get stuck" sometimes

### ISSUE THREAD

**Issue by stopmotio** [nextapps-de/winbox#16]
First of all, this is an awesome library and I am not downplaying that.

But if the mouse is moved out of the draggable area on one "frame" the window ignores any input until the user brings the mouse back, upon which it'll snap which is highly annoying.

**Comment by ts-thomas** [comment]
Thanks for the nice words, I'am appreciate it. This issue only occurs when using iframes as content body. I made some event capturing tests and find out that the mouse event will be "consumed" by the iframe when fast moving and release the mouse in a moment where the cursor is hovering the iframe (same window as well as other windows with an iframe), and does not bubble outside the iframe document, so the "mouseup" event is getting lost. I could fix that by adding additional "mouseleave" or "mousemove" event, but in then fast moving gets always interrupted immediately (but the issue has gone). That fix feels more like a downgrade, especially when not using iframe contents. I need to find another way to fix that.

**Comment by stopmotio** [comment]
I'm not entirely sure how any of this works but if this is possible try it:
Add div with a zindex lower than iframe
when we capture mousedown, we raise this transparent div to above the iframe

**Comment by Bader5110** [comment]
F

**Comment by Bader5110** [comment]
F

**Comment by Bader5110** [comment]
G

**Comment by Bader5110** [comment]
ｚ

**Comment by zamadatix** [comment]
This seems like an interesting fix candidate https://www.gyrocode.com/articles/how-to-detect-mousemove-event-over-iframe-element/

**Comment by ts-thomas** [comment]
@zamadatix very nice solution, thanks!

**Comment by ts-thomas** [comment]
It is now fixed in v0.1.91, that as an easy fix and it is really funny that I didn't came to this simple solution :)

**Comment by photonstorm** [comment]
Thank you so much for fixing this! I love Winbox but this issue was causing me grief. Glad to see it resolved so easily :)

**Comment by ts-thomas** [comment]
@photonstorm Thanks a lot for this hint. It is now fixed also.
