### ISSUE TITLE
Automated releases & CI

### ISSUE THREAD

**Issue by SamMousa** [nextapps-de/winbox#163]
Hey! Very cool library!

I see that you've not yet set up github actions to for fully automated releases & tests.
Nowadays this is actually very simple and definitely worth it if you want to reduce your maintenance load.

You could look at this repo for some inspiration: https://github.com/collecthor/collecthor-file-browser
I'd be happy to set it up in a PR here as well.

Note: for this to work properly you will need to use proper commit messages following a standard documented here: https://www.conventionalcommits.org/en/v1.0.0/

Cheers

**Comment by SamMousa** [comment]
@ts-thomas apologies for the rude ping. Do you have time to maintain this package? Is there any way in which the community or myself could help in terms of contributions?

If not that's also fine of course, but then we know to move ahead with our fork :-)

**Comment by ts-thomas** [comment]
Hey Sam, sorry for the late answer. If you like you can set it up :)
Thanks a lot, Thomas

**Comment by SamMousa** [comment]
Step 1: https://github.com/nextapps-de/winbox/pull/185

I have not been able to get the build working with google closure compiler:
```
Start build .....

src/js/template.js:38:8: WARNING - [JSC_TYPE_MISMATCH] assignment
found   : Element
required: null
  38|         template = document.createElement('div');
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

There might be more modern "hip" alternatives to google's compiler.

**Comment by SamMousa** [comment]
Closing this; we can continue in the relevant PRs.
