### ISSUE TITLE
Nested Open URL calls

### ISSUE THREAD

**Issue by justin-dx** [nextapps-de/winbox#18]
On the demo site, you can click to 'Open URI/URL' which displays the page in the windowed box. From this box clicking to 'Open URI/URL' displays an empty window box
Should I be able to click 'Open URI/URL' all the way down?

**Comment by ts-thomas** [comment]
That is a limitation of iFrame insertion. When you put the same page into an iframe again you can't open another instance of this inside this iframe. Because this would introduce the possibility of "endless iframe loops".

**Comment by Bader5110** [comment]
I
