### ISSUE TITLE
pointer locking?

### ISSUE THREAD

**Issue by AnxiousDarkly** [nextapps-de/winbox#19]
I do not believe the mouse should continue to scroll if you are dragging a window frame, seems like a strange UX, and I am pretty sure that you can use pointer locking to solve this.

**Comment by ts-thomas** [comment]
Can you describe your issue a bit more please? Is that issue related to this: #16 ?

**Comment by ts-thomas** [comment]
It should be fixed now in v0.1.91, thanks for the report.
