### ISSUE TITLE
[Feature Request] Ability to define iframe sandbox and feature-policies

### ISSUE THREAD

**Issue by photonstorm** [nextapps-de/winbox#20]
Hi - this is a superb library, thank you!

I love the `url` feature and the way it automatically creates an iframe, but it'd be great if I could specify the allow / feature-policy conditions somehow, too. In my case specifically, the iframe sandbox values are essential.

I can work around this by using the `html` property instead and creating my iframe with all its feature policies ahead of time, then setting it that way, but it would feel cleaner to keep it all within a single Winbox object config.

I appreciate you may consider this out of scope, in which case perhaps it would just be worth adding a note to the documentation instead, explaining that it's a basic iframe with no additional permissions?

**Comment by ts-thomas** [comment]
Did you mean the `allow` attribute of an iframe?

**Comment by photonstorm** [comment]
Yes, `allow`, `sandbox` and, to a lesser degree `referrerpolicy` are the most important.

Legacy ones like `allowfullscreen ` could be ignored.

**Comment by ts-thomas** [comment]
That are 3 attributes. The next developer needs further attributes so this doesn't scale well. For this purpose the library provides 2 methods for appending custom content/elements to the WinBox body:

1.
```js
new WinBox({
    html: '<iframe src="..." allow="..." sandbox="..." referrerpolicy="..."></iframe>'
});
```

2.
```js
new WinBox({
    mount: (function(){
        const iframe = document.createElement("iframe");
        // add your attributes ...
        return iframe;
    }())
});
```

Both of them could applied inside the WinBox config, as you mentioned. Also it's not really a deal breaker.
