### ISSUE TITLE
Angular input parameters

### ISSUE THREAD

**Issue by drewmperkins** [nextapps-de/winbox#24]
First, very nice work! I would consider this the best implementation of a web window manager.

I seem to be having issues with inputs using Angular.  I'm using cloneNode, but the url is always one WinBox behind.  

1. The first time I click to have it open a new WinBox it's blank
2. I close this WinBox
3. Click a different link
4. The new WinBox will open showing the previously clicked link.

```
this.url = this.sanitizer.bypassSecurityTrustResourceUrl(url);
new WinBox({
  mount: document.getElementById("iframeContent").cloneNode(true),
});
```

```
<div id="iframeContent" style="width:100%;height:100%">
  <iframe [src]='url' frameborder="0" style="height:100%;width:100%"></iframe>
</div>
```

I have noticed, I can wrap the new WinBox in a timeout and then everything works correctly, but that's not really a solution.  Any idea how inputs can be updated, and html content cloned, w/o using the timeout?

```
setTimeout(() => {
  new WinBox({
    mount: document.getElementById("iframeContent").cloneNode(true),
  });
}, 200);
```

I could of course change the way I'm using inputs with this iframe, but I would like to do something similar with an actual component, and then I would just run into the issue again because I need to pass the component input parameters.

**Comment by drewmperkins** [comment]
Property binding to components does not seem to work. I tried dynamically creating the component and assigning the parameters as well, but this didn't work either.

At the moment, I'm using a url and passing in parameters as a workaround...

**Comment by ts-thomas** [comment]
When you call mount() the node will be removed from the old position in DOM. In your example, when calling mount() Angular did not fully resolved their templating syntax so you will mount the iframe with template syntax. So yes it is blank, but when you inspect your DOM you will notice that the iframe was moved but has no src, because the template syntax did not resolve before. 

It is no issue with this library at all, it is a task for Angular. Since Angular completely runs asynchronously you have to use some kind of callbacks. You need to wait until Angular has processed the template syntax and then you can mount the node to the WinBox body.

**Comment by drewmperkins** [comment]
For performance reasons, I finally decided to tackle this issue in Angular, to my surprise this is now very easy to do in Angular v14.1 and greater.

The new introduction of createComponent works beautifully for WinBox.

```
import WinBox from "winbox/src/js/winbox";

constructor(private appRef: ApplicationRef, private injector: EnvironmentInjector) { }

const winBox = new WinBox({
      title: "TestTitle",
      x: "center",
      y: "center",
      width: "50%",
      height: "50%",
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      background: "#009ff2",
      border: 4,
});
const componentRef = createComponent(MaterialSpecReportComponent, {
  environmentInjector: this.injector,
  hostElement: winBox.body,
});
componentRef.setInput('myInput', 'test');
this.appRef.attachView(componentRef.hostView);
```

@ts-thomas  - I noticed you had info in the Readme now for Vue and React.. you may want to add a piece for Angular now as well.  Thanks for this library it's still working very well for our use case!
