### ISSUE TITLE
Usage in Next and React

### ISSUE THREAD

**Issue by HansKre** [nextapps-de/winbox#25]
Hi there,

what is the correct usage in ```Next.js``` and ```React.js```?

I have added dependency to my Next.js project by executing ```npm install winbox```

However, when I try to use it in my ```index.js```

```jsx
import WinBox from 'winbox'

export default function Home() {
  const handleClick = () => {
    new WinBox("Window Title");
  }

  return (
    <div>
      <button onClick={handleClick}>Open Winbox</button>
    </div>
  )
}
```

It gives me following error:

`
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/hans/git/Next/winbox-test/node_modules/winbox/src/js/winbox.js
require() of ES modules is not supported.
require() of /Users/hans/git/Next/winbox-test/node_modules/winbox/src/js/winbox.js from /Users/hans/git/Next/winbox-test/.next/server/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename winbox.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/hans/git/Next/winbox-test/node_modules/winbox/package.json.
`

Changing `import` to `require` does not solve the issue.
I have tried to import the ES6 version by ```import WinBox from 'winbox/src/js/winbox'``` as well, which didn't help either

**Comment by ts-thomas** [comment]
Please test a full qualified path to the "winbox.js" in your import.

```js
import WinBox from 'path/to/winbox.js'
```

Did you also try to follow the suggestions from your message, e.g. remove "type": "module" from the package.json?

**Comment by HansKre** [comment]
With `import WinBox from 'winbox'`

Error: `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/hans/git/Next/portfolio-hans/node_modules/winbox/src/js/winbox.js
require() of ES modules is not supported.
require() of /node_modules/winbox/src/js/winbox.js from /.next/server/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename winbox.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /node_modules/winbox/package.json.`

1a) remove "type": "module" from /node_modules/winbox/package.json:
Error: `/node_modules/winbox/src/js/winbox.js:9
import template from "./template.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module`

1b) rename winbox.js -> winbox.cjs

Error: `error - ./pages/index.js:4:0
Module not found: Can't resolve 'winbox'`

Additionally, change import to: `import WinBox from 'winbox/src/js/winbox.cjs'`

Error: `./node_modules/winbox/src/js/winbox.cjs
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (9:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| 
> import template from "./template.js";
| import { addListener, removeListener, setStyle, setText, getByClass, addClass, removeClass, preventEvent } from "./helper.js";
|`

2a) `import WinBox from '../node_modules/winbox/dist/winbox.bundle'

Error: `ReferenceError: document is not defined
    at eval (webpack-internal:///./node_modules/winbox/dist/winbox.bundle.js:9:34)
    at eval (webpack-internal:///./node_modules/winbox/dist/winbox.bundle.js:25:185)

2b) `import WinBox from '../node_modules/winbox/dist/js/winbox.min.js'`

Error: `ReferenceError: document is not defined
    at eval (webpack-internal:///./node_modules/winbox/dist/js/winbox.min.js:9:34)
    at eval (webpack-internal:///./node_modules/winbox/dist/js/winbox.min.js:24:185)`

2c) `import WinBox from '../node_modules/winbox/src/js/winbox'`

Error: `ReferenceError: document is not defined
    at eval (webpack-internal:///./node_modules/winbox/src/js/template.js:5:18)
    at Object../node_modules/winbox/src/js/template.js

**Comment by fzammetti** [comment]
Not sure if it'll help, but I'm using WinBox in a React-based app that also uses Webpack.  I'm using TypeScript though, so not sure if this will apply.  In the source file where I'm using WinBox, I have:

`import WinBox from "../../client/node_modules/winbox/src/js/winbox.js";`

My webpack.config.js is this:

```
const HtmlWebPackPlugin = require("html-webpack-plugin");
const path = require("path");
const webpack = require("webpack");

module.exports = {
  mode : "development",
  entry : "./src/index.ts",
  devtool : "inline-source-map",
  output : {
    filename : "main.js",
    path : path.resolve(__dirname, "dist"),
  },
  plugins : [
    new HtmlWebPackPlugin({ template : "./src/index.html", filename : "./index.html" })
  ],
  module : {
    rules : [
      {
        test : /\.tsx?$/,
        use : "ts-loader",
        exclude : /node_modules/
      },
      {
        test : /\.css$/i,
        use : [ "style-loader", "css-loader" ]
      }
    ]
  },
  resolve : {
    extensions : [ ".tsx", ".ts", ".js" ]
  }
};

```

I'm able to build in both dev and prod modes and everything works as expected, so hope something in there helps!

**Comment by RickoNoNo3** [comment]
Now [an entirely React-controlled component](https://github.com/RickoNoNo3/react-winbox) for WinBox is available. I want it to be better so if someone can try to use it and issue some problems, I will thanks a lot.
