### ISSUE TITLE
Can't drag boxes when position is set to absolute

### ISSUE THREAD

**Issue by Jacks349** [nextapps-de/winbox#27]
I just found out this library and i think it's magic, it's impressive how good it looks and how easy to use it is. 

I don't know if Winbox has another purpose compared to what i'm trying to do, but basically i'm trying to setup a page where i have a grid of more boxes in the same page, two for each row. In order to avoid the boxes to scroll when i scroll the page, i set `.winbox {position: absolute}`. The problem with this, is that when the position is absolute i can't drag the boxes. 

I was wondering if it's possible to have the boxes in absolute position, so that they won't scroll along with the page, while i can drag them too. Keep up the awesome work!

**Comment by ts-thomas** [comment]
Could you make a simple codepen for this?

**Comment by Jacks349** [comment]
@ts-thomas 
Alright, after trying again i managed to found that the problem was not winbox but another component messing with it (i'm using Winbox with VueJS).

Before closing the issue, i wanted to ask: when i'm using the windows in position absolute, is it possible to create or drag new windows for the whole length of the page instead of being able to place them only above the initial length of the page?

I don't know if what i'm saying is clear, so let me try to explain: when the position is absolute and my page is long, i cannot drag the windows after a certain height. Does it make sense? I can make a codepen or a video if it doesn't

**Comment by ts-thomas** [comment]
When you set absolute position your windows will fly around your scrollable page. That's a pretty unusual behavior for such windows. Maybe you could do a trick. Set the position of ".winbox" as absolute via CSS. Limit the viewport via negative values which will extend the viewport.

```js
new WinBox("Limit Viewport", {
    height: 500,
    bottom: -(document.body.scrollHeight - document.body.clientHeight)
});
```

You need to get the height of your scrollable content and substract the viewport height of it. Use the example above as a simple start.

**Comment by Jacks349** [comment]
That makes sense, thank you a lot @ts-thomas!

Just to share some background, what i'm trying to do is to create a grid of windows where each window is going to contain a component (i'm using VueJS), and winbox is a good choice due to how easy it is to drag and delete windows, something very similar to what [this library does](https://jbaysolutions.github.io/vue-grid-layout/).

Anyway, i'm sharing you an example where when the position is absolute and i set the height of the whole page from CSS, setting the height from Winbox won't work, i don't know if that's normal: https://codesandbox.io/s/great-mclean-7lbsq?file=/src/App.vue

Here i set the parent element to have a 5000px height, then i try to create a winbox with 100px height, but as you can see the window won't have an height of 100px
