### ISSUE TITLE
Resize don't works when a winbox is over another winbox

### ISSUE THREAD

**Issue by cesco69** [nextapps-de/winbox#35]
See this, the resize sometimes get stucked.

![frame-issue](https://user-images.githubusercontent.com/6096678/119368395-42c05180-bcb3-11eb-9e06-d45254441907.gif)

**Comment by photonstorm** [comment]
Yes, this is the same issue as with dragging windows with iframes, which was fixed previously, but still happens on resize events: https://github.com/nextapps-de/winbox/issues/16#issuecomment-837410003

**Comment by ts-thomas** [comment]
Thanks a lot for this nice video report. This is now fixed in the latest version.
