### ISSUE TITLE
Splitscreen bug

### ISSUE THREAD

**Issue by David-Carty** [nextapps-de/winbox#39]
Win 10, Chrome Version 91.0.4472.77 (Official Build) (64-bit) - (Very latest version)

When the right pane of a split pane minimizes (In the online demo), its title bar shrinks to 1px in width.  The left pane minimizes correctly.  This makes it very difficult to restore the right pane.

Using Chrome Dev Tools:

When both split panes are minimized:

left pane:

`<div id="winbox-1" class="winbox focus min" style="width: 251px;`

right pane:

`<div id="winbox-2" class="winbox min" style="width: 1px; `

**Comment by ts-thomas** [comment]
Thanks a lot for the report. It is now fixed. The npm package will be updated soon, please use the github sources in the meanwhile.
