### ISSUE TITLE
Is it possible to run VueJS code or Vue components inside of a window?

### ISSUE THREAD

**Issue by Jacks349** [nextapps-de/winbox#40]
Hello! First of all, thanks for working on this library, it's beautiful and fun to use. I'm trying to use Winbox to create a grid of draggable and resizable items in my VueJS application. 

I managed to create the windows quite easily, but the problem is that if i try to load anything dynamic or a Vue component, i can't interact with it, it looks like just the HTML is being loaded, so for example if i click on a button nothing works. Am i missing something or is this not supported by Winbox yet?

I'm importing the non bundled version: `import WinBox from "winbox/src/js/winbox.js";`

```
<div id="backstore" style="display: none">
    <div id="content">
        <someComponent/>
    </div>
</div>
...
mounted() {
    new WinBox("Mount DOM", {
        mount: document.getElementById("content").cloneNode(true)
    });
}
```

**Comment by Jacks349** [comment]
@ts-thomas Thank you! Yes indeed it "works" if i remove `cloneNode` but the optimal scenario would be to mount the component right into the window without having to declare the component in the template, since the point is to show the component only in the winbox and not in the template too, but i guess this is a Vue problem more than a winbox problem

**Comment by wobsoriano** [comment]
Made a component for this https://github.com/LinusBorg/vue-simple-portal.

It uses the native [teleport](https://v3.vuejs.org/api/built-in-components.html#teleport) component in Vue 3 and recommends https://github.com/LinusBorg/vue-simple-portal for Vue 2 users.
