### ISSUE TITLE
`hide()` and `show()` do not work

### ISSUE THREAD

**Issue by mossaiby** [nextapps-de/winbox#50]
`hide()` and `show()` do not work. The reason is that they add the class `hide` to the `WinBox` instance, and the rule `.winbox.hide` is not defined in CSS. There is a `.winbox.wb-hide` rule, but it is commented out. Also it would be nice to have an option to create a hidden window that can be shown later.

Thank you!

**Comment by ts-thomas** [comment]
.winbox.hide {
  display: none;
  visibility: hidden;
}
