### ISSUE TITLE
Content Security Policy directive: "frame-ancestors 'self'" when using url tag.

### ISSUE THREAD

**Issue by kmohamed1000** [nextapps-de/winbox#55]
I am trying to call a site using the url tag, however I keep getting the following error:

Refused to frame 'x' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'"

Is there a way to turn "frame-ancestors to 'none'?

new WinBox(menuItem.title, {
        background: "#000",
        border: 4,
        width: "75%",
        height: "65%",
        x: "center",
        y: "center",
        id: menuItem.menuID,
        title: menuItem.title,
        url: menuItem.path
      });

**Comment by wobsoriano** [comment]
Not possible to fix unless that website decides to change their Content-Security-Policy to allow your domain
