### ISSUE TITLE
mobile full screen

### ISSUE THREAD

**Issue by ali2b** [nextapps-de/winbox#58]
in case of mobile visitor click full screen button, how to return back to normal mode ?

**Comment by kodie** [comment]
@ali2b That's entirely dependent on the device. On Android, anytime a webpage goes into fullscreen, it tells you to swipe down from the top of the page and then press the back button. I just tested on my Android device and that seems to work fine.

You could however implement your own button to exit fullscreen by using `winbox.fullscreen(false)`.
