### ISSUE TITLE
translate and  height of WinBox

### ISSUE THREAD

**Issue by billyrudi** [nextapps-de/winbox#59]
Hi,
i have problem with WinBox
when i create a new window i obtain this
style="transform: translate(0px, 0px); width: 207px; height: 0px; z-index: 11;"
with hegth 0
and i'm not able to transalte it on the y axes.
can you help me?

**Comment by mossaiby** [comment]
@billyrudi Can you share some code or a fiddle?

**Comment by billyrudi** [comment]
[Archivio.zip](https://github.com/nextapps-de/winbox/files/7014063/Archivio.zip)
Hi,
this is a small project. The first problem is the rror on sturt up but after it if i execute   new WinBox("Window Title");
from console i see a close windows and i can not able to drag.

**Comment by mossaiby** [comment]
@billyrudi Oh, you're using React! That is the biggest problem. I think you need to use a React version of WinBox, such as https://www.npmjs.com/package/winbox-react. Hope this helps.

**Comment by billyrudi** [comment]
Idem with html... and framework7
[test.zip](https://github.com/nextapps-de/winbox/files/7014530/test.zip)
im sorry...

**Comment by mossaiby** [comment]
In your previous test, I was able to get round the problem by setting the parent `height` to `100vh`. I am looking into your new file. Indeed I am using WinBox with Framework7 right now! You missed the most important part of my comment (probably due to my edits!) you need to set `root` option. From my code with Framework7:
```
import 'winbox';

export const createToolWindow = (options, contentElement, hide, onCloseHandler) => {
  return new WinBox({
    ...options,
    root: document.querySelector('.page[data-name="main"]'),
    class: `ms-tool-window no-full no-max ${hide ? 'hide' : ''}`,
    mount: document.querySelector(`.page[data-name="main"] #${contentElement}`),
    onclose() {
      if (typeof onCloseHandler == 'function') {
        onCloseHandler();
      }
      this.hide();
      return true;
    }
  });
}
```
I'll take a look at your new code now.

**Comment by mossaiby** [comment]
The issue is the same here. The parent height (here, `body`) is 0. This solved the problem for me:
![image](https://user-images.githubusercontent.com/27294271/130081858-4845462e-8660-4404-bdf6-bf589696358f.png)
Hope this helps!

**Comment by mossaiby** [comment]
Glad to hear that helped you!
