### ISSUE TITLE
Why can't a modal window be resized, moved or displayed full screen?

### ISSUE THREAD

**Issue by Kukulkano** [nextapps-de/winbox#72]
I want a modal window but people should be able to maximize or resize/move. The content of the window is displaying some sort of code editor for HTML and during this they should not manipulate other things. But allowing resize is really important here.

How come this is disabled for modal windows? Or is this just for the demo and can get enabled/disabled if needed? Or is there a good reason for that?

**Comment by Kukulkano** [comment]
:-) The purpose of making something modal is not locking the window. It is mainly preventing users from using the underlying form elements. Please have a look here: [https://en.wikipedia.org/wiki/Modal_window](https://en.wikipedia.org/wiki/Modal_window)
But making it non movable or non-resizable is definitely not the purpose of modal windows.

Anyway, thanks for the winbox code. The workaround works and maybe in a future version this is optional for modal windows ;-)

**Comment by jcubic** [comment]
I think that there is some misunderstanding. Because I also have broken library I can't resize the window or move it, up down. Only left and right works.

https://codepen.io/jcubic/pen/gOGmZLq
