### ISSUE TITLE
No Icons

### ISSUE THREAD

**Issue by blurdylan** [nextapps-de/winbox#8]
I added Winbox to my vue app,

Everything works well functionally however, i have the control icons do not show up. I can maximize, minimize etc but the icons just doesn't show up.

I checked the css in dev tools and I see a strange issue

<img width="450" alt="image" src="https://user-images.githubusercontent.com/26802924/116667654-bb760b80-a99c-11eb-81b0-b15a8ff3221d.png">

**Comment by ts-thomas** [comment]
Please use the non-bundled version: https://github.com/nextapps-de/winbox#use-non-bundled-version
