### ISSUE TITLE
HTML parameter will not work with ```

### ISSUE THREAD

**Issue by DylanAlloy** [nextapps-de/winbox#86]
If you're like me and have newlines representing more HTML, triple backticks (typical javascript syntax) will break the DOM of the winbox.

Not sure why.

**Comment by kodie** [comment]
@DylanAlloy Could you provide an example? As far as I know, triple backticks aren't used in JavaScript at all and are more of a Markdown thing. Single backticks work just fine:

```js
new WinBox('New Window', {
  html: `Here's
some content
let's see
if it
works`
})
```
