### ISSUE TITLE
Creating window from inside another window

### ISSUE THREAD

**Issue by vpetit-reimagine** [nextapps-de/winbox#87]
Hello,

It seems it is impossible to focus a window that is created from inside a previous window, as the index of the previous window will always be higher than the newly created window.

This is a serious issue as it doesn't allow to create a modal window with children windows.

Even if you use the `.focus()` method on the child window right after creating it, it doesn't work.

Would it be possible to change this behaviour?

Thanks.

**Comment by kodie** [comment]
@vpetit-reimagine It seems if you put a 1 millisecond timeout on the focus of the newly opened modal it works, not ideal but it's a workaround for now.

```js
function openNewWindow () {
  var newWin = new WinBox('Second Window')
  
  setTimeout(function () {
    newWin.focus()
  }, 1)
}

window.addEventListener('load', function () {
  new WinBox('First Window', {
    html: '<button type="button" onclick="openNewWindow()">Open New Window</button>'
  })
})
```

**Comment by vpetit-reimagine** [comment]
I found another solution and just do `event.stopPropagation();` on all buttons of a popup (that creates new popups).

Still not perfect, but I think it's pretty decent
