### ISSUE TITLE
winbox iframe onload  ?

### ISSUE THREAD

**Issue by MadTomT** [nextapps-de/winbox#88]
Hi 
I can see there is onclose and onfocus, is there anyway to do an onload function ?
I'm loading a page in to an iframe, but I want to delete a couple of elements from the page..  To do that the page has to be loaded.

So onload, would allow that to work.

Thanks

**Comment by kodie** [comment]
@MadTomT This seems to work:

```js
var iframeModal = new WinBox('WinBox.js', {
  url: 'https://nextapps-de.github.io/winbox/'
})

iframeModal.body.firstChild.onload = function () {
  console.log('it loaded')
}
```

**Comment by ts-thomas** [comment]
The "onload" event is now supported by default for the iframe usecase. To target the specific iframe you need to use `this` within your event handler.
