### ISSUE TITLE
Window disappears when minimized

### ISSUE THREAD

**Issue by alaindesilets** [nextapps-de/winbox#90]
[winbox-bug.html.txt](https://github.com/nextapps-de/winbox/files/7522920/winbox-bug.html.txt)

Under specific circumstances, a winbox window disappears altogether when you minimize it. This is illustrated by the attached winbox-bug.html file (you will need to remove the .txt extension to load it into a browser).

Note that the problem does not happen if I comment out either of the:
- DOCTYPE tag at the start of the page
- The bunch of 'hello' lines that force the appearance of a scroll bar on the whole web page

Not sure why those things cause a bug, because the index.html file that comes with winbox has both of those charactertics, and it does not suffer from the bug.

**Comment by ezzkht** [comment]
I had the same issue. It happens when the page content has a scroll.
The main cause is the code at line 620 & 621 in winbox.js :
```
root_w = body.clientWidth;
root_h = body.clientHeight;
```
It should be replaced with:
```
root_w = window.innerWidth;
root_h = window.innerHeight;
```

**Comment by ts-thomas** [comment]
This is now fixed and also keeps track of the scrollbar-width which can reduce the window.innerWidth as available space.
